/**
 * Created by session2 on 10/8/15.
 */
google.setOnLoadCallback(drawRegionsMap);

function drawRegionsMap() {

    var data = google.visualization.arrayToDataTable([
        ['Country', 'Life Expectancy'],
        ['Afghanistan', 60],
        ['Albania', 74],
        ['Algeria', 72],
        ['Andorra', 83],
        ['Angola', 51],
        ['Antigua and Barbuda',75],
        ['Argentina', 76],
        ['Armenia', 71],
        ['Australia', 83],
        ['Austria', 81],
        ['Azerbaijan', 72],
        ['Bahamas',75],
        ['Bahrain', 77],
        ['Bangladesh', 70],
        ['Barbados', 78],
        ['Belarus', 72],
        ['Belgium', 80],
        ['Belize',75],
        ['Benin', 59],
        ['Bhutan', 68],
        ['Bolivia', 68],
        ['Bosnia and Herzegovina', 77],
        ['Botswana', 62],
        ['Brazil',74],
        ['Brunei Darussalam', 77],
        ['Bulgaria', 74],
        ['Burkina Faso', 58],
        ['Burundi', 56],
        ["Côte d'lvoire", 53],
        ['Cabo Verde',74],
        ['Cambodia', 72],
        ['Cameroon', 56],
        ['Canada', 82],
        ['Central African Republic', 51],
        ['Chad', 51],
        ['China',75],
        ['Colombia', 79],
        ['Comoros', 62],
        ['Congo', 59],
        ['Cook Islands', 76],
        ['Costa Rica', 79],
        ['Croatia',78],
        ['Cuba', 79],
        ['Cyprus', 82],
        ['Czech Republic', 78],
        ["Democratic People's Republic of Korea", 70],
        ['Democratic Republic of the Congo', 52],
        ['Denmark',80],
        ['Djibouti', 61],
        ['Dominica', 75],
        ['Dominican Republic', 77],
        ['Ecuador', 75],
        ['Egypt', 71],
        ['El Salvador',72],
        ['Equatorial Guinea', 55],
        ['Eritrea', 63],
        ['Estonia', 77],
        ['Ethiopia', 64],
        ['Fiji', 69],
        ['Finland',81],
        ['France', 82],
        ['Gabon', 63],
        ['Gambia', 61],
        ['Georgia', 74],
        ['Germany', 81],
        ['Ghana',62],
        ['Greece', 81],
        ['Grenada', 73],
        ['Guatemala', 72],
        ['Guinea', 58],
        ['Guinea-Bissau', 54],
        ['Guyana',63],
        ['Haiti', 62],
        ['Honduras', 74],
        ['Hungary', 72],
        ['Iceland', 82],
        ['India', 66],
        ['Indonesia',71],
        ['Iran (Islamic Republic of)', 74],
        ['Iraq', 70],
        ['Ireland', 81],
        ['Israel', 82],
        ['Italy', 83],
        ['Jamaica',74],
        ['Japan', 84],
        ['Jordan', 74],
        ['Kazakhstan', 68],
        ['Kenya', 61],
        ['Kiriati', 66],
        ['Kuwait',78],
        ['Kyrgystan', 69],
        ["Lao People's Democratic Republic", 66],
        ['Latvia', 74],
        ['Lebanon', 80],
        ['Lesotho', 50],
        ['Liberia',62],
        ['Libya', 75],
        ['Lithuania', 74],
        ['Luxembourg', 82],
        ['Madagascar', 64],
        ['Malawi', 59],
        ['Malaysia',74],
        ['Maldives', 77],
        ['Mali', 57],
        ['Malta', 81],
        ['Marshall Islands', 70],
        ['Mauritania', 63],
        ['Mauritius',74],
        ['Mexico', 76],
        ['Micronesia', 69],
        ['Monaco', 82],
        ['Mongolia', 67],
        ['Montenegro', 76],
        ['Morocco',71],
        ['Mozambique', 53],
        ['Myanmar', 66],
        ['Namibia', 67],
        ['Nauru', 79],
        ['Nepal', 68],
        ['Netherlands',81],
        ['New Zealand', 82],
        ['Nicaragua', 73],
        ['Niger', 59],
        ['Nigeria', 54],
        ['Niue', 74],
        ['Norway',82],
        ['Oman', 76],
        ['Pakistan', 65],
        ['Palau', 73],
        ['Panama', 77],
        ['Papua New Guinea', 62],
        ['Paraguay',75],
        ['Peru', 77],
        ['Philippiness', 69],
        ['Poland', 77],
        ['Portugal', 81],
        ['Qatar', 79],
        ['Republic of Korea',81],
        ['Republic of Moldova', 71],
        ['Romania', 74],
        ['Russian Federation', 69],
        ['Rwanda', 65],
        ['Saint Kitts and Nevis', 74],
        ['Saint Lucia',75],
        ['Saint Vincent and the Grenadines', 74],
        ['Samoa', 73],
        ['San Marino', 83],
        ['Sao Tome and Principe', 67],
        ['Saudi Arabi', 76],
        ['Senegal',64],
        ['Serbia', 75],
        ['Seychelles', 74],
        ['Sierra Leone', 46],
        ['Singapore', 83],
        ['Slovakia', 76],
        ['Slovenia',80],
        ['Solomon Islands', 69],
        ['Somalia', 53],
        ['South Africa', 59],
        ['South Sudan', 55],
        ['Spain', 82],
        ['Sri Lanka',75],
        ['Sudan', 63],
        ['Suriname', 77],
        ['Swaziland', 54],
        ['Sweden', 82],
        ['Switzerland', 83],
        ['Syrian Arab Republic',68],
        ['Tajikistan', 68],
        ['Thailand', 75],
        ['Yuglosav republic of Macedonia', 76],
        ['Timor-Leste', 83],
        ['Togo', 58],
        ['Tonga',71],
        ['Trinidad and Tobago', 70],
        ['Tunisia', 76],
        ['Turkey', 75],
        ['Turkmenistan',63],
        ['Tuvalu', 68],
        ['Uganda', 57],
        ['Ukraine', 71],
        ['United Arab Emirates', 76],
        ['Great Britain and Northern Ireland', 81],
        ['United Republic of Tanzania',61],
        ['United States of America', 79],
        ['Uruguay', 77],
        ['Uzbekistan', 69],
        ['Vanuatu',72],
        ['Venezuela', 76],
        ['Vietnam', 76],
        ['Yemen', 64],
        ['Zambia', 57],
        ['Zimbabwe', 58],


    ]);

    var options = {};

    var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

    chart.draw(data, options);
}
google.setOnLoadCallback(drawChart);
function drawChart() {

    var data = google.visualization.arrayToDataTable([
        ['Country', 'Life Expectancy'],
        ['Afghanistan', 60],
        ['Albania', 74],
        ['Algeria', 72],
        ['Andorra', 83],
        ['Angola', 51],
        ['Antigua and Barbuda',75],
        ['Argentina', 76],
        ['Armenia', 71],
        ['Australia', 83],
        ['Austria', 81],
        ['Azerbaijan', 72],
        ['Bahamas',75],
        ['Bahrain', 77],
        ['Bangladesh', 70],
        ['Barbados', 78],
        ['Belarus', 72],
        ['Belgium', 80],
        ['Belize',75],
        ['Benin', 59],
        ['Bhutan', 68],
        ['Bolivia', 68],
        ['Bosnia and Herzegovina', 77],
        ['Botswana', 62],
        ['Brazil',74],
        ['Brunei Darussalam', 77],
        ['Bulgaria', 74],
        ['Burkina Faso', 58],
        ['Burundi', 56],
        ["Côte d'lvoire", 53],
        ['Cabo Verde',74],
        ['Cambodia', 72],
        ['Cameroon', 56],
        ['Canada', 82],
        ['Central African Republic', 51],
        ['Chad', 51],
        ['China',75],
        ['Colombia', 79],
        ['Comoros', 62],
        ['Congo', 59],
        ['Cook Islands', 76],
        ['Costa Rica', 79],
        ['Croatia',78],
        ['Cuba', 79],
        ['Cyprus', 82],
        ['Czech Republic', 78],
        ["Democratic People's Republic of Korea", 70],
        ['Democratic Republic of the Congo', 52],
        ['Denmark',80],
        ['Djibouti', 61],
        ['Dominica', 75],
        ['Dominican Republic', 77],
        ['Ecuador', 75],
        ['Egypt', 71],
        ['El Salvador',72],
        ['Equatorial Guinea', 55],
        ['Eritrea', 63],
        ['Estonia', 77],
        ['Ethiopia', 64],
        ['Fiji', 69],
        ['Finland',81],
        ['France', 82],
        ['Gabon', 63],
        ['Gambia', 61],
        ['Georgia', 74],
        ['Germany', 81],
        ['Ghana',62],
        ['Greece', 81],
        ['Grenada', 73],
        ['Guatemala', 72],
        ['Guinea', 58],
        ['Guinea-Bissau', 54],
        ['Guyana',63],
        ['Haiti', 62],
        ['Honduras', 74],
        ['Hungary', 72],
        ['Iceland', 82],
        ['India', 66],
        ['Indonesia',71],
        ['Iran (Islamic Republic of)', 74],
        ['Iraq', 70],
        ['Ireland', 81],
        ['Israel', 82],
        ['Italy', 83],
        ['Jamaica',74],
        ['Japan', 84],
        ['Jordan', 74],
        ['Kazakhstan', 68],
        ['Kenya', 61],
        ['Kiriati', 66],
        ['Kuwait',78],
        ['Kyrgystan', 69],
        ["Lao People's Democratic Republic", 66],
        ['Latvia', 74],
        ['Lebanon', 80],
        ['Lesotho', 50],
        ['Liberia',62],
        ['Libya', 75],
        ['Lithuania', 74],
        ['Luxembourg', 82],
        ['Madagascar', 64],
        ['Malawi', 59],
        ['Malaysia',74],
        ['Maldives', 77],
        ['Mali', 57],
        ['Malta', 81],
        ['Marshall Islands', 70],
        ['Mauritania', 63],
        ['Mauritius',74],
        ['Mexico', 76],
        ['Micronesia', 69],
        ['Monaco', 82],
        ['Mongolia', 67],
        ['Montenegro', 76],
        ['Morocco',71],
        ['Mozambique', 53],
        ['Myanmar', 66],
        ['Namibia', 67],
        ['Nauru', 79],
        ['Nepal', 68],
        ['Netherlands',81],
        ['New Zealand', 82],
        ['Nicaragua', 73],
        ['Niger', 59],
        ['Nigeria', 54],
        ['Niue', 74],
        ['Norway',82],
        ['Oman', 76],
        ['Pakistan', 65],
        ['Palau', 73],
        ['Panama', 77],
        ['Papua New Guinea', 62],
        ['Paraguay',75],
        ['Peru', 77],
        ['Philippiness', 69],
        ['Poland', 77],
        ['Portugal', 81],
        ['Qatar', 79],
        ['Republic of Korea',81],
        ['Republic of Moldova', 71],
        ['Romania', 74],
        ['Russian Federation', 69],
        ['Rwanda', 65],
        ['Saint Kitts and Nevis', 74],
        ['Saint Lucia',75],
        ['Saint Vincent and the Grenadines', 74],
        ['Samoa', 73],
        ['San Marino', 83],
        ['Sao Tome and Principe', 67],
        ['Saudi Arabi', 76],
        ['Senegal',64],
        ['Serbia', 75],
        ['Seychelles', 74],
        ['Sierra Leone', 46],
        ['Singapore', 83],
        ['Slovakia', 76],
        ['Slovenia',80],
        ['Solomon Islands', 69],
        ['Somalia', 53],
        ['South Africa', 59],
        ['South Sudan', 55],
        ['Spain', 82],
        ['Sri Lanka',75],
        ['Sudan', 63],
        ['Suriname', 77],
        ['Swaziland', 54],
        ['Sweden', 82],
        ['Switzerland', 83],
        ['Syrian Arab Republic',68],
        ['Tajikistan', 68],
        ['Thailand', 75],
        ['Yuglosav republic of Macedonia', 76],
        ['Timor-Leste', 83],
        ['Togo', 58],
        ['Tonga',71],
        ['Trinidad and Tobago', 70],
        ['Tunisia', 76],
        ['Turkey', 75],
        ['Turkmenistan',63],
        ['Tuvalu', 68],
        ['Uganda', 57],
        ['Ukraine', 71],
        ['United Arab Emirates', 76],
        ['Great Britain and Northern Ireland', 81],
        ['United Republic of Tanzania',61],
        ['United States of America', 79],
        ['Uruguay', 77],
        ['Uzbekistan', 69],
        ['Vanuatu',72],
        ['Venezuela', 76],
        ['Vietnam', 76],
        ['Yemen', 64],
        ['Zambia', 57],
        ['Zimbabwe', 58],

    ]);

    var options = {
        pieHole: 0.5,
        pieSliceTextStyle: {
            color: 'black',
        },
        legend: 'none'
    };

    var chart = new google.visualization.PieChart(document.getElementById('donut_single'));
    chart.draw(data, options);
}